language: node_js
node_js:
- v10.16.0
before_install:
- npm install -g typescript@3.5.3
before_deploy:
- npm run build
- cd preact_build
deploy:
  skip_cleanup: true
  provider: heroku
  app: preact-typescript-pwa-starter
  api_key:
    secure: pYqLMogsEyMj7MwLnGv6U/bC7KYb/WoK9O47LnbBdk1vtQgivSIYd8jv53gBFPYasOLYI0wsL35uHuGRSYB3K8ASwTEa89kmlroWetwtlixDScRN3Y1A/Df0V5CuEnk8OjUarvICYu1h6EPEoRTei+Fjghe1LbBm0v2G3aFBzexEKJDMwafHkGeRPuvpnEBp60w2EODdA6Ra1q12JkyzYWEar2E0KTnSoQoTwK1xXjLk9sqskqrcMmI6yAJti4RCqJtMHHky4j6IrPR0Sv0ms95Qol+SzUQfcCcneOvs57EDIdXOQrWNHm8h05A58GaDeNrHO1xTCJRQIvyxsRuHMv3qO2404b/ex/684qp/N4m//Mmgq4CIpD+x02iO6psiNJ7kRUccrs2PK6nHSseAPqtx09EYcyRs0eLKTPt6m20EiSAAORo/nLzOdEWtxMiu4xrrTXAYTEQNj2ReWbw5oUcWP+ZlQXv83P9F+sI5eW+6BVNezj+5Ne4DdJo8ARJNmbDmsHdFm2xdpVUmmgyedsX0lWBkINvsUPPXHnO48HfeZEnzS4LgMgo6oGqfyExA+oR1ZDwdFilpxFsAS7jBtHga28vV/+XBmkNgzVrwlBv90OB7mbzo5Bw2eBJfG/5y7yasKrSPrXo62XqSVfQ5UQUcPl7EHpaweXf8q6WLPJY=
